theme: jekyll-theme-chirpy
theme_mode: dark

lang: ko-KR
timezone: Asia/Seoul

title: 카모뜨린 아지트
tagline: 포기하면 거기서 깁업
description: 기록을 빙자한 일방적 독백
avatar: /assets/img/ProfileImage.png
logo: /assets/img/ProfileImage.png
url: 'https://Mascari4615.github.io'
baseurl:

github:
  username: Mascari4615

google_site_verification: google_meta_tag_verification # change to your verification string

google_analytics:
  id: 'G-QRNK1L0YH7'
  pv:
    proxy_endpoint:   # fill in the Google Analytics superProxy endpoint of Google App Engine
    cache_path:       # the local PV cache data, friendly to visitors from GFW region

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url will be added to all image (site avatar & posts' images) paths starting with '/'
# e.g. 'https://cdn.com'
# e.g. 'https://cdn.jsdelivr.net/gh/cotes2020/chirpy-images@0a003683c0c3ca549d12c309f9b3e03ea20981e5'
img_cdn: ''

toc: true

paginate: 12

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - '*.json'

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/